name: Sysdig IaC Scan

on:
  push:
    branches:
      - main

jobs:
  iac-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Install Sysdig CLI Scanner
      - name: Install Sysdig CLI Scanner
        run: |
          curl -L -o ./sysdig-cli-scanner https://download.sysdig.com/scanner/latest/sysdig-cli-scanner
          chmod +x ./sysdig-cli-scanner

      # Step 3: Run IaC Scan with Sysdig
      - name: Run IaC Scan
        env:
          SECURE_API_TOKEN: ${{ secrets.SYSDIG_API_TOKEN }}
        run: |
          ./sysdig-cli-scanner --iac . --apiurl https://secure.sysdig.com

